version: '3'

services:
  cfractions-pypy:
    build:
      context: .
      args:
        - IMAGE_NAME=${PYPY_IMAGE_NAME}
        - IMAGE_VERSION=${PYPY_IMAGE_VERSION}
    image: lycantropos/cfractions-cpython:2.6.1
    volumes:
      - ./pyproject.toml:/opt/cfractions/pyproject.toml
      - ./README.md:/opt/cfractions/README.md
      - ./setup.py:/opt/cfractions/setup.py
      - ./tests:/opt/cfractions/tests
      - ./cfractions:/opt/cfractions/cfractions
    entrypoint: pytest
